config/routes.rb
Rails.application.routes.draw do
  root to: 'characters#home'
  resources :characters
  resources :items
  resources :enemies
  resources :locations
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :items, as: :imageable
end

app/models/enemy.rb
class Enemy < ApplicationRecord
  belongs_to :location

  scope :by_location, -> (location_parameter) do
    where("location_id = #{location_parameter}") 
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :items, as: :imageable

  def self.start_room
    self.all.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authorize
    if current_user
      if !current_user.admin
        flash[:alert] = "You aren't authorized to visit that page."
        redirect_to '/'
      end
    end
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  def index
    @characters = Character.all
  end

  def home

  end

  # GET /characters/1
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character, notice: 'Character was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /characters/1
  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'Character was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /characters/1
  def destroy
    @character.destroy
    redirect_to characters_url, notice: 'Character was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def character_params
      params.require(:character).permit(:name, :type, :hp, :damage, :user_id)
    end
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :authorize
  before_action :set_enemy, only: [:show, :edit, :update, :destroy]

  # GET /enemies
  def index
    @enemies = Enemy.all
  end

  # GET /enemies/1
  def show
  end

  # GET /enemies/new
  def new
    @enemy = Enemy.new
  end

  # GET /enemies/1/edit
  def edit
  end

  # POST /enemies
  def create
    @enemy = Enemy.new(enemy_params)

    if @enemy.save
      redirect_to @enemy, notice: 'Enemy was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /enemies/1
  def update
    if @enemy.update(enemy_params)
      redirect_to @enemy, notice: 'Enemy was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /enemies/1
  def destroy
    @enemy.destroy
    redirect_to enemies_url, notice: 'Enemy was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enemy
      @enemy = Enemy.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def enemy_params
      params.require(:enemy).permit(:name, :hp, :damage, :location_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @locations = Location.all
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :effect, :value, :imageable_type, :imageable_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authorize, only: [:index, :new, :edit, :create, :update, :destroy]
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
    @enemies = Enemy.by_location(params[:id])

  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:room, :description, :door)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/enemies_helper.rb
module EnemiesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
  </div>

  <div class="field">
    <%= form.label :damage %>
    <%= form.number_field :damage %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/home.html.erb
<% if user_signed_in? %>
<%= link_to 'Start Game', location_path(Location.start_room) %>
<% else %>
<%= link_to 'Sign In', new_user_session_path %>
<% end %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Hp</th>
      <th>Damage</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.name %></td>
        <td><%= character.type %></td>
        <td><%= character.hp %></td>
        <td><%= character.damage %></td>
        <td><%= character.user_id %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @character.type %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @character.hp %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @character.damage %>
</p>

<p>
  <strong>User:</strong>
  <%= @character.user_id %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/enemies/_form.html.erb
<%= form_with(model: enemy, local: true) do |form| %>
  <% if enemy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enemy.errors.count, "error") %> prohibited this enemy from being saved:</h2>

      <ul>
      <% enemy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
  </div>

  <div class="field">
    <%= form.label :damage %>
    <%= form.number_field :damage %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enemies/edit.html.erb
<h1>Editing Enemy</h1>

<%= render 'form', enemy: @enemy %>

<%= link_to 'Show', @enemy %> |
<%= link_to 'Back', enemies_path %>

app/views/enemies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enemies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hp</th>
      <th>Damage</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enemies.each do |enemy| %>
      <tr>
        <td><%= enemy.name %></td>
        <td><%= enemy.hp %></td>
        <td><%= enemy.damage %></td>
        <td><%= enemy.location %></td>
        <td><%= link_to 'Show', enemy %></td>
        <td><%= link_to 'Edit', edit_enemy_path(enemy) %></td>
        <td><%= link_to 'Destroy', enemy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enemy', new_enemy_path %>

app/views/enemies/new.html.erb
<h1>New Enemy</h1>

<%= render 'form', enemy: @enemy %>

<%= link_to 'Back', enemies_path %>

app/views/enemies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enemy.name %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @enemy.hp %>
</p>

<p>
  <strong>Damage:</strong>
  <%= @enemy.damage %>
</p>

<p>
  <strong>Location:</strong>
  <%= @enemy.location %>
</p>

<%= link_to 'Edit', edit_enemy_path(@enemy) %> |
<%= link_to 'Back', enemies_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :effect %>
    <%= form.text_field :effect %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <input type="hidden" name="item[imageable_type]" value="Location">


  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :imageable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Effect</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.effect %></td>
        <td><%= item.value %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Effect:</strong>
  <%= @item.effect %>
</p>

<p>
  <strong>Value:</strong>
  <%= @item.value %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpg</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container">
    <div class="jumbotron">
      <h1>Welcome to the <br><strong>Space Marine Fighter Battle Death Match</strong><br>RPG</h1>
    </div>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>

  </div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :door %>
    <%= form.text_field :door %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Room</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.room %></td>
        <td><%= location.description %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @location.room %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<% doors = @location.door.split(',').map { |d| d.to_i } %>
<% if doors.length > 0 %>
  <% doors.each do |door| %>
    <h3><%= link_to "Door #{door}", location_path(Location.find(door)) %></h3>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>